### ISSUE TITLE
Apply Proposal Schema to Subgraph

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#41]
## What

Schema was defined in issue 31 and implemented in the summoner app.
https://github.com/HausDAO/daohaus-rage/issues/31

## Todo

- [ ] Add json parsing to createProposal mapping
- [ ] Title, description, proposalURI and content type
- [ ] nullable fields or default if it doesn't match the schema

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-v3-subgraph-sandbox/commit/461f9875573a29ceb67186d394cef55e3f40b4fe
