### ISSUE TITLE
Revisit Styling Approach (Styled Components)

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-rage#43]
## What

- Before moving forward with Radix and Stitches we want to dive a bit deeper into the pros and cons of Styled Components over Stitches for the styling solution. This is a short duration Rage to explore this topic a bit further to ensure that we make the best decision possible for our needs in the component library.

## TODOs

- [x] Experiment with using Styled Components with Radix instead of Stitches
- [x] Build out a component using Radix and Styled Components
- [x] Create a basic theme object that we can build from

## Deliverables

- Short demo showing the above TODOs
- Brief knowledge share on learnings

**Comment by earth2travis** [comment]
What needs to be done here?

**Comment by earth2travis** [comment]
Made the decision to move forward with 💅
