### ISSUE TITLE
Deploy Rage Storybook

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-rage#46]
## What

Deploy the Rage Storybook to either [Chromatic](https://www.chromatic.com/), GitHub Pages, or s3. Chromatic is a free cloud host from the Storybook maintainers. 

We can start with Chromatic, GitHub Pages, or s3 and then maybe look at using Skynet or a decentralized host like Fleek.

## TODOs

- [ ] Determine deploy target 
- [ ] Add deploy command to root `package.json`
- [ ] Add deploy workflow to GitHub Actions

## Deliverables

Storybook build commands added to the root's `package.json` and a hosted Storybook instance with CI/CD based on the `haus-components` package.

## Resources

- https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/

**Comment by earth2travis** [comment]
Not need because of https://github.com/HausDAO/daohaus-monorepo/issues/36
