### ISSUE TITLE
Audit Utils Package Scope

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-rage#52]
# Overview

As we spin up a new common utility library we want to audit the current needs and potentials utilities so we can categorize and look for opportunities to break up a utilities package into small pieces. 

## Notes from spec working session
https://hackmd.io/wtDwRLeVTsepeDjeiQ0lyg?edit

```
    - **TODO: need to review V2 and upcoming V3 to try and get a larger list and organize by functional area. But some of these will emerge as we build**
        - would an audit be helpful at this point -- creating an ongoing list?
        - this can then become the TODO list and as folks are Raging/Saging they would mark it off the list -- it can then be added to our `utils`

- [ ] full util audit
    - in rage
    - in v2
    - package breakdown suggestion
    - How do we want to run the audit? Who wants to work on this? create a Hackmd with a list / categorize these and prioritize
    - Create a one-pager on this process

```

## Todos

1. Audit current utility landscape
- [ ] Create a wiki page or hack.md to capture a list of potential utilities and constants
- [ ] Review current utilities used in haus-sdk package, summon-app and core ui app and add to the list
- [ ] Review utilities in v2 app and add to the list

2. Define process for on-going utility request/adds
